export { ReactComponent as ContactIcon } from "./contact.svg";
export { ReactComponent as NotSelectedIcon } from "./not-selected.svg";
export { ReactComponent as NotificationIcon } from "./notification.svg";
export { ReactComponent as NotificationFillIcon } from "./notification-fill.svg";
export { ReactComponent as SelectedIcon } from "./select.svg";
export { ReactComponent as CaretDownIcon } from "./caret-down.svg";
export { ReactComponent as OptionIcon } from "./option.svg";
export { ReactComponent as OptionWhiteIcon } from "./option-white.svg";
export { ReactComponent as PlayIcon } from "./play.svg";
